/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author ymber
 */
public class TelaOrdemDeServico extends javax.swing.JFrame {

    /**
     * Creates new form TelaOrdemDeServico
     */
    public TelaOrdemDeServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_numero_ordem = new javax.swing.JTextField();
        txt_id_funcionario = new javax.swing.JTextField();
        btn_cadastrar_nota = new javax.swing.JButton();
        txt_data_solicitacao1 = new javax.swing.JTextField();
        txt_id_funcionario2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txt_data_solicitacao2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(190, 190, 190));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NUMERO ORDEM");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("PLACA CARRO");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("VALOR TOTAL");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel17.setFont(new java.awt.Font("Thumbs Down", 1, 24)); // NOI18N
        jLabel17.setText("ItCars");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 131, -1));

        jLabel18.setFont(new java.awt.Font("Thumbs Down", 1, 10)); // NOI18N
        jLabel18.setText("notas fiscais");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 46, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("CPF");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("CODIGO FUNCIONÁRIO");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("DESCRIÇÃO");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("DATA SERVIÇO");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        txt_numero_ordem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numero_ordemActionPerformed(evt);
            }
        });
        jPanel3.add(txt_numero_ordem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 47, 30));

        txt_id_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_funcionarioActionPerformed(evt);
            }
        });
        jPanel3.add(txt_id_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 270, 30));

        btn_cadastrar_nota.setBackground(new java.awt.Color(102, 102, 102));
        btn_cadastrar_nota.setText("CADASTRAR");
        btn_cadastrar_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_notaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cadastrar_nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 120, 80));

        txt_data_solicitacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_data_solicitacao1ActionPerformed(evt);
            }
        });
        jPanel3.add(txt_data_solicitacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 210, 30));

        txt_id_funcionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_funcionario2ActionPerformed(evt);
            }
        });
        jPanel3.add(txt_id_funcionario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 80, 30));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 390, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 420, 80));

        txt_data_solicitacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_data_solicitacao2ActionPerformed(evt);
            }
        });
        jPanel3.add(txt_data_solicitacao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_data_solicitacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_data_solicitacao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_data_solicitacao2ActionPerformed

    private void txt_id_funcionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_funcionario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_funcionario2ActionPerformed

    private void txt_data_solicitacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_data_solicitacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_data_solicitacao1ActionPerformed

    private void btn_cadastrar_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_notaActionPerformed
        // TODO add your handling code here:
        /* acesso.conecta();
        String pedido;
        pedido = "insert into tb_notas_fiscais (ordemnumero, idcliente, idfuncionario, datasolicitacao, dataprevisaoconclusao, descricao) values ('"+txt_numero_ordem.getText()+"','"+txt_id_cliente.getText()+"','"+txt_id_funcionario.getText()+"', '"+txt_data_solicitacao.getText()+"', '"+txt_data_conclusao.getText()+"', '"+txt_descricao.getText()+"')";
        acesso.executa(pedido);
        acesso.fechaConexao();
        */
    }//GEN-LAST:event_btn_cadastrar_notaActionPerformed

    private void txt_id_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_funcionarioActionPerformed

    private void txt_numero_ordemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numero_ordemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numero_ordemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOrdemDeServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar_nota;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_data_solicitacao1;
    private javax.swing.JTextField txt_data_solicitacao2;
    private javax.swing.JTextField txt_id_funcionario;
    private javax.swing.JTextField txt_id_funcionario2;
    private javax.swing.JTextField txt_numero_ordem;
    // End of variables declaration//GEN-END:variables
}
